project_id = "cshazxfkbjcsdxgznpde"

[functions.process-quiz-image]
verify_jwt = true

[functions.solve-chemistry]
verify_jwt = true

[functions.generate-reaction]
verify_jwt = false

[functions.generate-book-quiz]
verify_jwt = false

[functions.process-book-pdf]
verify_jwt = false
